### PR TITLE
Update quickpoll.py

### PR DESCRIPTION
**Pull request by Stupid-Benz**
Make Poll ID Shorter, Using Base 64 
Link: https://github.com/windowsboy111/merlin-py/issues/8

### CODE REVIEW

**Comment by windowsboy111** [comment]
I am testing it

**Comment by windowsboy111** [comment]
there are bugs in the system. you even cannot end it.

**Comment by windowsboy111** [comment]
the id becomes longer

**Comment by Stupid-Benz** [comment]
Becuz used utf8 and then changed to base 64

**Comment by windowsboy111** [comment]
can you try ASCII?

**Comment by windowsboy111** [comment]
Why do you close this

**Comment by windowsboy111** [comment]
why don't you commit directly to this request again and then let me pull it instead of opening a new one?

**Pull request closed without merging**
